# Inserts a blank line between shell prompts
add_newline = true

# Move the directory to the second line
format="$all$directory$character"

#format = "$all"

# Which is equivalent to
#format = """
#$username\
#$hostname\
#$shlvl\
#$singularity\
#$kubernetes\
#$directory\
#$vcsh\
#$git_branch\
#$git_commit\
#$git_state\
#$git_metrics\
#$git_status\
#$hg_branch\
#$docker_context\
#$package\
#$cmake\
#$cobol\
#$dart\
#$deno\
#$dotnet\
#$elixir\
#$elm\
#$erlang\
#$golang\
#$helm\
#$java\
#$julia\
#$kotlin\
#$lua\
#$nim\
#$nodejs\
#$ocaml\
#$perl\
#$php\
#$purescript\
#$python\
#$rlang\
#$red\
#$ruby\
#$rust\
#$scala\
#$swift\
#$terraform\
#$vlang\
#$vagrant\
#$zig\
#$nix_shell\
#$conda\
#$memory_usage\
#$aws\
#$gcloud\
#$openstack\
#$env_var\
#$crystal\
#$custom\
#$cmd_duration\
#$line_break\
#$jobs\
#$battery\
#$time\
#$status\
#$shell\
#$character"""
#

[shell]
fish_indicator = "🐟"
#powershell_indicator = "_"
unknown_indicator = "mystery shell"
#style = "cyan bold"
disabled = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

#[env_var.SHELL]
#variable = "SHELL"
#default = "unknown shell"
#[env_var.USER]
#default = "unknown user"

# ~/.config/starship.toml

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

# ~/.config/starship.toml

[memory_usage]
disabled = false
threshold = 75
symbol = "🎛"
style = "bold  red"
format = '$symbol  [$ram_pct](bold red) '

[nodejs]
symbol = ""
