#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Make Caps Lock an additional Esc and both Shift Keys toggle Caps Lock
setxkbmap -option caps:escape,shift:both_capslock &

# Start clipmenu
systemctl --user import-environment DISPLAY

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a fim state=floating 
bspc rule -a ranger state=floating 
bspc rule -a gpick state=floating 
bspc rule -a mpv state=floating 

#AutoStart
sxhkd &
#xpad &
#picom &
$HOME/.config/polybar/launch.sh
feh --bg-fill --randomize ~/Pictures/wallpapers/*
